debuggin 2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -60,15 +60,17 @@ jobs:
             # Navigate to the server directory and stop the old server (if running)
             cd ${{ secrets.SERVER_PATH }} || echo "cannot change to directory"
             touch "beforekill.txt"
+            
             # kill server if another one is running
-            pgrep -f 'java -jar CDDemo-1.0-SNAPSHOT.jar' > /dev/null
-  
-            if [ $? -eq 0 ]; then
-              echo "Process found, attempting to kill..."
-              pkill -f 'java -jar CDDemo-1.0-SNAPSHOT.jar' || echo "Failed to kill process"
+            PID=$(pgrep -f 'java -jar CDDemo-1.0-SNAPSHOT.jar')
+
+            # Check if the PID was found
+            if [ -n "$PID" ]; then
+              echo "Process found with PID $PID, attempting to kill..."
+              kill $PID || echo "Failed to kill process"
             else
               echo "No process to kill"
-              fi
+            fi
             touch "afterkill.txt"
             # Start the new server
             nohup java -jar ${{ secrets.SERVER_PATH }}/CDDemo-1.0-SNAPSHOT.jar > output.log 2>&1 &
